### ISSUE TITLE
This the package is pointless no offence

### ISSUE THREAD

**Issue by busterbeam** [zackees/static_ffmpeg#3]
Yes FFMPEG is a binary package, Python is a scripting language...  How is your package on PyPI?  This does nothing.  FFMPEG has separate binaries for each platform like the python (binary) interpreter is different on every platform.  please explain why is super important?

**Comment by zackees** [comment]
Oh it's pointless huh? Better go tell the npm ffmpeg-static guys who see 100k+ weekly downloads for the equivalent tool in node.

https://www.npmjs.com/package/ffmpeg-static

It turns out that ffmpeg isn't as easy to deploy cross-platform as `pip install static_ffmpeg` is here. That's why it exists, to be used as a sub component for a larger product. And it's tested too on Win/Mac/Ubuntu on every push.
