### ISSUE TITLE
[non-issue] `static-ffmpeg` plugin for `ffmpegio`

### ISSUE THREAD

**Issue by tikuma-lsuhsc** [zackees/static_ffmpeg#8]
@zackees - This isn't an issue but just a heads-up as earlier you showed interests in my `ffmpegio` package. I just released a plugin which let you use `static-ffmpeg` binary automatically.

Here is the link to the repo:

[https://github.com/python-ffmpegio/python-ffmpegio-plugin-static-ffmpeg](https://github.com/python-ffmpegio/python-ffmpegio-plugin-static-ffmpeg)

**Comment by zackees** [comment]
Thanks this is great!

I see this is a plugin. Previously this static_ffmpeg library had a high 100MB install size, but I brought this down to 12kB, added ffprobe, and now the ffmpeg/ffprobe binaries are only downloaded on first call to the api call to probe for the binaries:

```
from static_ffmpeg import run
# Platform binaries are installed on the first run of below.
ffmpeg, ffprobe = run.get_or_fetch_platform_executables_else_raise()
```

Would you now consider including static_ffmpeg since I've implemented these feature sets for your use case and brought down the install size?

Thanks!
~Zach

**Comment by tikuma-lsuhsc** [comment]
Sorry, but no I won't, and there is a very good reason for it. I'm a heavy user of venv with multiple projects going at once, so I prefer to keep the total install size (across my work environment) in check, and the design of `static-ffmpeg` requires every venv to download and install ~100 MB of files. I see that it works for some people's python usage, so I wanted to make this plugin.

That being said, well-done on getting the download mechanism to work!

**Comment by zackees** [comment]
Great, thanks for the response.
